services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: agrosensor
      POSTGRES_PASSWORD: agrosensorpassword
      POSTGRES_DB: agrosensor-iot
    ports:
      - "5432:5432"
    networks:
      - agrosensor_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agrosensor -d agrosensor-iot"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: agrosensor_backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/agrosensor-iot
      SPRING_DATASOURCE_USERNAME: agrosensor
      SPRING_DATASOURCE_PASSWORD: agrosensorpassword
    depends_on:
      db:
        condition: service_healthy
    networks:
      - agrosensor_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  esp32-sim:
    build:
      context: ./docker-iot/
      dockerfile: Dockerfile
    container_name: esp32-sim
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - agrosensor_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - agrosensor_net

networks:
  agrosensor_net:
    driver: bridge
