version: "1"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: agrosensor
      POSTGRES_PASSWORD: agrosensorpassword
      POSTGRES_DB: agrosensor-iot
    ports:
      - "5432:5432"
    #    volumes:
    #      - postgres_data:/var/lib/postgresql/data
    networks:
      - agrosensor_net

  #volumes:
  #  postgres_data:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - db
    networks:
      - agrosensor_net



networks:
  agrosensor_net:
    driver: bridge